env:
  browser: true
  es2021: true
  jest: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: 0
  import/extensions: 0
  no-underscore-dangle: 0
  linebreak-style: 0
  semi: [2, "never"]                 # ИЗМЕНИТЬ: never вместо always
  arrow-parens: [2, "as-needed"]     # ИЗМЕНИТЬ: as-needed вместо always
ignorePatterns:
  - node_modules/
